clone_folder: c:\gopath\src\github.com\sensu\sensu-go

branches:
  only:
    - master

image:
  - Visual Studio 2015
  # - Visual Studio 2017

cache:
  - c:\go\pkg\mod -> go.mod, go.sum

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.13.15
  GO111MODULE: 'on'
  GOPROXY: 'https://proxy.golang.org'

  matrix:
    - GOARCH: amd64
      TEST_SUITE: unit
    - GOARCH: amd64
      TEST_SUITE: integration

install:
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-%GOARCH%.msi
  - msiexec /i go%GOVERSION%.windows-%GOARCH%.msi /q
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - mkdir %GOPATH%\bin
  - go mod download

platform:
  - x64

build_script:
  - ps: .\build.ps1 $env:TEST_SUITE
