clone_folder: c:\gopath\src\github.com\sensu\sensu-go

branches:
  only:
    - master

image:
  - Visual Studio 2015
  # - Visual Studio 2017

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.10.2

  matrix:
    - GOARCH: amd64
      TEST_SUITE: unit
    - GOARCH: amd64
      TEST_SUITE: integration

install:
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-%GOARCH%.msi
  - msiexec /i go%GOVERSION%.windows-%GOARCH%.msi /q
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - mkdir %GOPATH%\bin

platform:
  - x64

build_script:
  - ps: .\build.ps1 $env:TEST_SUITE

before_deploy:
  - ps: .\build.ps1 wait_for_appveyor_jobs

deploy:
  provider: GitHub
  release: $(appveyor_repo_tag_name)
  description: ''
  artifact: /sensu.*/
  auth_token:
    secure: e3aSzq/Y9btOgFMXc3rfGwjPLj/LnxyG8KY6czcrywgQXEm+9X74fvGFE0B9Km/j
  draft: false
  prerelease: true
  on:
    appveyor_repo_tag: true
