clone_folder: c:\gopath\src\github.com\sensu\sensu-go

branches:
  only:
    - master

image:
  - Visual Studio 2015
  # - Visual Studio 2017

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.9

  matrix:
    - GOARCH: 386
      TEST_SUITE: unit
      GOGC: off
    - GOARCH: amd64
      TEST_SUITE: unit
      GOGC: off
    - GOARCH: 386
      TEST_SUITE: e2e
      GOGC: off
    - GOARCH: amd64
      TEST_SUITE: e2e
      GOGC: off

install:
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.msi
  - msiexec /i go%GOVERSION%.windows-amd64.msi /q
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin\windows_386;%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - ps: .\build.ps1 deps
  - ps: .\build.ps1 build_tools

platform:
  - x64

build_script:
  - ps: .\build.ps1 $env:TEST_SUITE
