version: '3'
services:
  backend1:
    image: sensu/sensu:master
    command: sensu-backend start --etcd-listen-client-urls http://0.0.0.0:2379 --etcd-name backend1 --etcd-initial-cluster backend1=http://backend1:2380,backend2=http://backend2:2380,backend3=http://backend3:2380 --etcd-initial-cluster-state new --etcd-initial-advertise-peer-urls http://backend1:2380 --state-dir /var/lib/sensu/etcd1 --etcd-listen-peer-urls http://0.0.0.0:2380 --log-level debug
    hostname: backend1
    restart: always
    ports:
      - "2379:2379"
      - "2380:2380"
      - "8080:8080"
      - "8081:8081"
  backend2:
    image: sensu/sensu:master
    command: sensu-backend start --etcd-listen-client-urls http://0.0.0.0:2379 --etcd-name backend2 --etcd-initial-cluster backend1=http://backend1:2380,backend2=http://backend2:2380,backend3=http://backend3:2380 --etcd-initial-cluster-state new --etcd-initial-advertise-peer-urls http://backend2:2380 --state-dir /var/lib/sensu/etcd2 --etcd-listen-peer-urls http://0.0.0.0:2380 --log-level debug
    hostname: backend2
    restart: always
    ports:
      - "12379:2379"
      - "12380:2380"
      - "18080:8080"
      - "18081:8081"
  backend3:
    image: sensu/sensu:master
    command: sensu-backend start --etcd-listen-client-urls http://0.0.0.0:2379 --name backend3 --etcd-initial-cluster backend1=http://backend1:2380,backend2=http://backend2:2380,backend3=http://backend3:2380 --etcd-initial-cluster-state new --etcd-initial-advertise-peer-urls http://backend3:2380 --state-dir /var/lib/sensu/etcd3 --etcd-listen-peer-urls http://0.0.0.0:2380 --log-level debug
    hostname: backend3
    restart: always
    ports:
      - "22379:2379"
      - "22380:2380"
      - "28080:8080"
      - "28081:8081"
  agent1:
    image: sensu/sensu:master
    command: sensu-agent start --backend-url ws://backend1:8081 --subscriptions test --log-level debug
    hostname: agent1
    restart: always
    depends_on:
      - backend1
      - backend2
      - backend3
  agent2:
    image: sensu/sensu:master
    command: sensu-agent start --backend-url ws://backend2:8081 --subscriptions test --log-level debug
    hostname: agent2
    restart: always
    depends_on:
      - backend1
      - backend2
      - backend3
  agent3:
    image: sensu/sensu:master
    command: sensu-agent start --backend-url ws://backend3:8081 --subscriptions test --log-level debug
    hostname: agent3
    restart: always
    depends_on:
      - backend1
      - backend2
      - backend3
